version: '3.8'

services:
  kaizeneka-api:
    build:
      context: ./KaizenekaApi
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped