import '../../models/progress_models.dart';
import '../../models/task_models.dart';
import '../services/supabase_service.dart';
import 'package:flutter/foundation.dart';

class NarrativeService {
  // Cache for narrative missions
  static List<NarrativeMission>? _cachedMissions;

  // Get all narrative missions from database
  static Future<List<NarrativeMission>> getAllMissions() async {
    if (_cachedMissions != null) {
      return _cachedMissions!;
    }

    try {
      final response = await SupabaseService.client
          .from('narrative_missions')
          .select()
          .eq('is_active', true)
          .order('order_in_phase');

      _cachedMissions = response.map<NarrativeMission>((json) {
        return NarrativeMission(
          id: json['id'],
          title: json['title'],
          description: json['description'],
          principle: json['principle'],
          arc: Arc.values.firstWhere((a) => a.name == json['arc']),
          phase: json['phase'],
          order: json['order_in_phase'],
          difficulty: Difficulty.values.firstWhere(
            (d) => d.name == json['difficulty'],
            orElse: () => Difficulty.medium,
          ),
          xpReward: json['xp_reward'] ?? 0,
          coinsReward: json['coins_reward'] ?? 0,
          tags: List<String>.from(json['tags'] ?? []),
        );
      }).toList();

      return _cachedMissions!;
    } catch (e) {
      debugPrint('Error fetching narrative missions: $e');
      return [];
    }
  }

  // Legacy static list for backward compatibility (deprecated)
  static final List<NarrativeMission> allMissions = [
    // FASE 1 – EL DESPERTAR (Arco 1)
    NarrativeMission(
      id: 'despertar_1',
      title: 'Identifica tus 3 RDPs más obvias',
      description: 'Reconoce tus Rendijas de Palme más evidentes que te roban tiempo y energía.',
      principle: 'Conciencia del Palme',
      arc: Arc.despertar,
      phase: 1,
      order: 1,
      difficulty: Difficulty.medium,
      xpReward: 15,
      coinsReward: 3,
      tags: ['autodiagnóstico', 'conciencia'],
    ),
    NarrativeMission(
      id: 'despertar_2',
      title: 'Desinstala una app de palme',
      description: 'Elimina una aplicación que sabes que te distrae innecesariamente.',
      principle: 'Conciencia del Palme',
      arc: Arc.despertar,
      phase: 1,
      order: 2,
      difficulty: Difficulty.easy,
      xpReward: 10,
      coinsReward: 2,
      tags: ['desintoxicación', 'acción'],
    ),
    NarrativeMission(
      id: 'despertar_3',
      title: 'Crea tu "Declaración Antipalme"',
      description: 'Escribe una declaración personal contra el palme y tu compromiso con el cambio.',
      principle: 'Conciencia del Palme',
      arc: Arc.despertar,
      phase: 1,
      order: 3,
      difficulty: Difficulty.medium,
      xpReward: 15,
      coinsReward: 3,
      tags: ['compromiso', 'escritura'],
    ),
    NarrativeMission(
      id: 'despertar_4',
      title: 'Día sin quejarte ni justificarte',
      description: 'Pasa un día completo aceptando las situaciones sin quejas ni excusas.',
      principle: 'Autoobservación',
      arc: Arc.despertar,
      phase: 1,
      order: 4,
      difficulty: Difficulty.hard,
      xpReward: 25,
      coinsReward: 5,
      tags: ['disciplina', 'aceptación'],
    ),
    NarrativeMission(
      id: 'despertar_5',
      title: 'Limpieza simbólica de tu entorno',
      description: 'Limpia y organiza tu espacio físico como metáfora de limpieza mental.',
      principle: 'Autoobservación',
      arc: Arc.despertar,
      phase: 1,
      order: 5,
      difficulty: Difficulty.medium,
      xpReward: 15,
      coinsReward: 3,
      tags: ['limpieza', 'simbólico'],
    ),
    NarrativeMission(
      id: 'despertar_6',
      title: 'Observa un pensamiento sin juzgarlo',
      description: 'Durante 10 minutos, observa tus pensamientos como un espectador neutral.',
      principle: 'Autoobservación',
      arc: Arc.despertar,
      phase: 1,
      order: 6,
      difficulty: Difficulty.medium,
      xpReward: 15,
      coinsReward: 3,
      tags: ['meditación', 'conciencia'],
    ),
    NarrativeMission(
      id: 'despertar_7',
      title: 'Crea tu mapa de energía semanal',
      description: 'Registra tus niveles de energía hora por hora durante una semana.',
      principle: 'Autoobservación',
      arc: Arc.despertar,
      phase: 1,
      order: 7,
      difficulty: Difficulty.medium,
      xpReward: 20,
      coinsReward: 4,
      tags: ['registro', 'energía'],
    ),
    NarrativeMission(
      id: 'despertar_8',
      title: 'Registra tus hábitos PPM',
      description: 'Identifica y registra tus hábitos de Palme Por Minuto.',
      principle: 'Autoobservación',
      arc: Arc.despertar,
      phase: 1,
      order: 8,
      difficulty: Difficulty.easy,
      xpReward: 10,
      coinsReward: 2,
      tags: ['registro', 'hábitos'],
    ),
    NarrativeMission(
      id: 'despertar_9',
      title: 'Mide tu tiempo real de ocio improductivo',
      description: 'Cronometra exactamente cuánto tiempo dedicas al ocio que no te nutre.',
      principle: 'Autoobservación',
      arc: Arc.despertar,
      phase: 1,
      order: 9,
      difficulty: Difficulty.medium,
      xpReward: 15,
      coinsReward: 3,
      tags: ['medición', 'conciencia'],
    ),
    NarrativeMission(
      id: 'despertar_10',
      title: 'Escoge tu mentor o guía',
      description: 'Selecciona una figura inspiradora que te guíe en tu camino Kaizeneka.',
      principle: 'Autoobservación',
      arc: Arc.despertar,
      phase: 1,
      order: 10,
      difficulty: Difficulty.easy,
      xpReward: 10,
      coinsReward: 2,
      tags: ['mentoría', 'inspiración'],
    ),

    // FASE 2 – ENTRENAMIENTO (Arco 2)
    NarrativeMission(
      id: 'entrenamiento_1',
      title: 'Define tus OVCs personales',
      description: 'Establece tus Objetivos Vitales Clave para las próximas semanas.',
      principle: 'Disciplina y energía',
      arc: Arc.entrenamiento,
      phase: 2,
      order: 1,
      difficulty: Difficulty.medium,
      xpReward: 20,
      coinsReward: 4,
      tags: ['planificación', 'objetivos'],
    ),
    NarrativeMission(
      id: 'entrenamiento_2',
      title: 'Optimiza tu mañana',
      description: 'Crea una rutina matinal de 30 minutos que te prepare para el día.',
      principle: 'Disciplina y energía',
      arc: Arc.entrenamiento,
      phase: 2,
      order: 2,
      difficulty: Difficulty.medium,
      xpReward: 20,
      coinsReward: 4,
      tags: ['rutina', 'mañana'],
    ),
    NarrativeMission(
      id: 'entrenamiento_3',
      title: 'Mantén 3 hábitos saludables una semana',
      description: 'Establece y mantén tres hábitos positivos durante 7 días consecutivos.',
      principle: 'Disciplina y energía',
      arc: Arc.entrenamiento,
      phase: 2,
      order: 3,
      difficulty: Difficulty.hard,
      xpReward: 30,
      coinsReward: 6,
      tags: ['hábitos', 'consistencia'],
    ),
    NarrativeMission(
      id: 'entrenamiento_4',
      title: 'Una semana sin multitarea',
      description: 'Dedícate completamente a una tarea a la vez durante 7 días.',
      principle: 'Disciplina y energía',
      arc: Arc.entrenamiento,
      phase: 2,
      order: 4,
      difficulty: Difficulty.hard,
      xpReward: 30,
      coinsReward: 6,
      tags: ['enfoque', 'productividad'],
    ),
    NarrativeMission(
      id: 'entrenamiento_5',
      title: 'Activa "Ganasolina Full Tank"',
      description: 'Realiza actividades que recarguen completamente tu energía vital.',
      principle: 'Disciplina y energía',
      arc: Arc.entrenamiento,
      phase: 2,
      order: 5,
      difficulty: Difficulty.medium,
      xpReward: 20,
      coinsReward: 4,
      tags: ['energía', 'recarga'],
    ),
    NarrativeMission(
      id: 'entrenamiento_6',
      title: 'Aprende a decir "no" sin culpa',
      description: 'Practica rechazar compromisos que no aporten valor a tu vida.',
      principle: 'Disciplina y energía',
      arc: Arc.entrenamiento,
      phase: 2,
      order: 6,
      difficulty: Difficulty.medium,
      xpReward: 20,
      coinsReward: 4,
      tags: ['límites', 'autoconfianza'],
    ),
    NarrativeMission(
      id: 'entrenamiento_7',
      title: 'Mide tu productividad real',
      description: 'Registra y analiza tu tiempo productivo vs tiempo total disponible.',
      principle: 'Disciplina y energía',
      arc: Arc.entrenamiento,
      phase: 2,
      order: 7,
      difficulty: Difficulty.medium,
      xpReward: 20,
      coinsReward: 4,
      tags: ['medición', 'productividad'],
    ),
    NarrativeMission(
      id: 'entrenamiento_8',
      title: 'Registra tus victorias diarias',
      description: 'Cada noche, anota 3 cosas positivas que lograste ese día.',
      principle: 'Disciplina y energía',
      arc: Arc.entrenamiento,
      phase: 2,
      order: 8,
      difficulty: Difficulty.easy,
      xpReward: 10,
      coinsReward: 2,
      tags: ['gratitud', 'registro'],
    ),
    NarrativeMission(
      id: 'entrenamiento_9',
      title: 'Mantén tu energía en balance 3 días',
      description: 'Equilibra alimentación, ejercicio y descanso durante 72 horas.',
      principle: 'Disciplina y energía',
      arc: Arc.entrenamiento,
      phase: 2,
      order: 9,
      difficulty: Difficulty.hard,
      xpReward: 30,
      coinsReward: 6,
      tags: ['equilibrio', 'energía'],
    ),
    NarrativeMission(
      id: 'entrenamiento_10',
      title: 'Reto: Dormir 8h tres noches seguidas',
      description: 'Consigue dormir 8 horas completas durante 3 noches consecutivas.',
      principle: 'Disciplina y energía',
      arc: Arc.entrenamiento,
      phase: 2,
      order: 10,
      difficulty: Difficulty.hard,
      xpReward: 35,
      coinsReward: 7,
      tags: ['sueño', 'disciplina'],
    ),

    // FASE 3 – DISCIPLINA (Arcos 3 y 7)
    NarrativeMission(
      id: 'disciplina_1',
      title: 'Diseña tu rutina NK personalizada',
      description: 'Crea una rutina completa basada en los principios Kaizeneka.',
      principle: 'Autodominio físico y mental',
      arc: Arc.disciplina,
      phase: 3,
      order: 1,
      difficulty: Difficulty.hard,
      xpReward: 35,
      coinsReward: 7,
      tags: ['rutina', 'personalización'],
    ),
    NarrativeMission(
      id: 'disciplina_2',
      title: 'Mantén una racha de 14 días',
      description: 'Completa tus hábitos diarios durante 14 días sin interrupciones.',
      principle: 'Autodominio físico y mental',
      arc: Arc.disciplina,
      phase: 3,
      order: 2,
      difficulty: Difficulty.hard,
      xpReward: 40,
      coinsReward: 8,
      tags: ['racha', 'consistencia'],
    ),
    NarrativeMission(
      id: 'disciplina_3',
      title: 'Elimina un hábito tóxico',
      description: 'Identifica y elimina completamente un hábito que te perjudica.',
      principle: 'Autodominio físico y mental',
      arc: Arc.disciplina,
      phase: 3,
      order: 3,
      difficulty: Difficulty.hard,
      xpReward: 35,
      coinsReward: 7,
      tags: ['eliminación', 'cambio'],
    ),
    NarrativeMission(
      id: 'disciplina_4',
      title: 'Aplica "Esfuerzo Inteligente"',
      description: 'Trabaja más eficientemente, no más duro, durante una semana.',
      principle: 'Consistencia',
      arc: Arc.disciplina,
      phase: 3,
      order: 4,
      difficulty: Difficulty.medium,
      xpReward: 25,
      coinsReward: 5,
      tags: ['eficiencia', 'inteligencia'],
    ),
    NarrativeMission(
      id: 'disciplina_5',
      title: 'Crea tu sistema de recompensas',
      description: 'Diseña un sistema de recompensas que te motive consistentemente.',
      principle: 'Consistencia',
      arc: Arc.disciplina,
      phase: 3,
      order: 5,
      difficulty: Difficulty.medium,
      xpReward: 25,
      coinsReward: 5,
      tags: ['recompensas', 'motivación'],
    ),
    NarrativeMission(
      id: 'disciplina_6',
      title: 'Entrena cuando menos quieras',
      description: 'Completa una sesión de ejercicio cuando tu motivación esté en el mínimo.',
      principle: 'Consistencia',
      arc: Arc.disciplina,
      phase: 3,
      order: 6,
      difficulty: Difficulty.hard,
      xpReward: 30,
      coinsReward: 6,
      tags: ['disciplina', 'entrenamiento'],
    ),
    NarrativeMission(
      id: 'disciplina_7',
      title: 'Registra tu progreso con honestidad',
      description: 'Mantén un registro diario honesto de tus avances y retrocesos.',
      principle: 'Consistencia',
      arc: Arc.disciplina,
      phase: 3,
      order: 7,
      difficulty: Difficulty.medium,
      xpReward: 20,
      coinsReward: 4,
      tags: ['honestidad', 'registro'],
    ),
    NarrativeMission(
      id: 'disciplina_8',
      title: 'Crea un ritual matinal de 3 pasos',
      description: 'Establece un ritual de 3 pasos que marques el inicio de tu día.',
      principle: 'Consistencia',
      arc: Arc.disciplina,
      phase: 3,
      order: 8,
      difficulty: Difficulty.medium,
      xpReward: 20,
      coinsReward: 4,
      tags: ['ritual', 'mañana'],
    ),
    NarrativeMission(
      id: 'disciplina_9',
      title: 'Semana sin azúcar ni farfolla digital',
      description: 'Elimina el azúcar refinado y limita el scrolling innecesario por 7 días.',
      principle: 'Consistencia',
      arc: Arc.disciplina,
      phase: 3,
      order: 9,
      difficulty: Difficulty.hard,
      xpReward: 35,
      coinsReward: 7,
      tags: ['eliminación', 'semana'],
    ),
    NarrativeMission(
      id: 'disciplina_10',
      title: 'Rompe la cadena de excusas',
      description: 'Durante 24 horas, enfréntate a cada excusa con acción inmediata.',
      principle: 'Consistencia',
      arc: Arc.disciplina,
      phase: 3,
      order: 10,
      difficulty: Difficulty.hard,
      xpReward: 30,
      coinsReward: 6,
      tags: ['excusas', 'acción'],
    ),

    // FASE 4 – SINERGIA (Arcos 4 y 8)
    NarrativeMission(
      id: 'sinergia_1',
      title: 'Detecta tus TDRs naturales',
      description: 'Identifica tus Talentos, Dones y Recursos únicos.',
      principle: 'TDRs y equilibrio integral',
      arc: Arc.sinergia,
      phase: 4,
      order: 1,
      difficulty: Difficulty.medium,
      xpReward: 25,
      coinsReward: 5,
      tags: ['autodescubrimiento', 'talentos'],
    ),
    NarrativeMission(
      id: 'sinergia_2',
      title: 'Mejora un área sin tocarla directamente',
      description: 'Trabaja en una área relacionada para mejorar otra indirectamente.',
      principle: 'TDRs y equilibrio integral',
      arc: Arc.sinergia,
      phase: 4,
      order: 2,
      difficulty: Difficulty.medium,
      xpReward: 25,
      coinsReward: 5,
      tags: ['sinergia', 'indirecto'],
    ),
    NarrativeMission(
      id: 'sinergia_3',
      title: 'Semana de equilibrio entre salud, amor y trabajo',
      description: 'Dedica tiempo equilibrado a tus tres JVCs durante 7 días.',
      principle: 'TDRs y equilibrio integral',
      arc: Arc.sinergia,
      phase: 4,
      order: 3,
      difficulty: Difficulty.hard,
      xpReward: 35,
      coinsReward: 7,
      tags: ['equilibrio', 'jvc'],
    ),
    NarrativeMission(
      id: 'sinergia_4',
      title: 'Crea tu "Estrategia de Equilibrio Vital"',
      description: 'Diseña una estrategia personal para mantener el equilibrio entre tus áreas vitales.',
      principle: 'Inteligencia Integral',
      arc: Arc.sinergia,
      phase: 4,
      order: 4,
      difficulty: Difficulty.hard,
      xpReward: 35,
      coinsReward: 7,
      tags: ['estrategia', 'equilibrio'],
    ),
    NarrativeMission(
      id: 'sinergia_5',
      title: 'Observa cómo tu salud afecta tu productividad',
      description: 'Registra durante una semana cómo tu estado físico impacta tu trabajo.',
      principle: 'Inteligencia Integral',
      arc: Arc.sinergia,
      phase: 4,
      order: 5,
      difficulty: Difficulty.medium,
      xpReward: 25,
      coinsReward: 5,
      tags: ['observación', 'conexión'],
    ),
    NarrativeMission(
      id: 'sinergia_6',
      title: 'Hackea tu entorno social',
      description: 'Optimiza tu círculo social para apoyar tus objetivos.',
      principle: 'Inteligencia Integral',
      arc: Arc.sinergia,
      phase: 4,
      order: 6,
      difficulty: Difficulty.medium,
      xpReward: 25,
      coinsReward: 5,
      tags: ['redes', 'optimización'],
    ),
    NarrativeMission(
      id: 'sinergia_7',
      title: 'Crea una rutina de triple mejora',
      description: 'Establece una rutina que mejore simultáneamente cuerpo, mente y relaciones.',
      principle: 'Equilibrio holístico',
      arc: Arc.sinergia,
      phase: 4,
      order: 7,
      difficulty: Difficulty.hard,
      xpReward: 35,
      coinsReward: 7,
      tags: ['rutina', 'triple'],
    ),
    NarrativeMission(
      id: 'sinergia_8',
      title: 'Practica "1 + 1 + 1 > 3"',
      description: 'Combina actividades de diferentes áreas para crear sinergia mayor.',
      principle: 'Equilibrio holístico',
      arc: Arc.sinergia,
      phase: 4,
      order: 8,
      difficulty: Difficulty.medium,
      xpReward: 25,
      coinsReward: 5,
      tags: ['sinergia', 'combinación'],
    ),
    NarrativeMission(
      id: 'sinergia_9',
      title: 'Mide tu energía integral diaria',
      description: 'Registra tu energía física, mental, emocional y social cada día.',
      principle: 'Equilibrio holístico',
      arc: Arc.sinergia,
      phase: 4,
      order: 9,
      difficulty: Difficulty.medium,
      xpReward: 20,
      coinsReward: 4,
      tags: ['medición', 'integral'],
    ),
    NarrativeMission(
      id: 'sinergia_10',
      title: 'Integra el aprendizaje con la acción',
      description: 'Aplica inmediatamente lo que aprendes en tus actividades diarias.',
      principle: 'Equilibrio holístico',
      arc: Arc.sinergia,
      phase: 4,
      order: 10,
      difficulty: Difficulty.medium,
      xpReward: 25,
      coinsReward: 5,
      tags: ['aprendizaje', 'acción'],
    ),

    // FASE 5 – DISOLUCIÓN (Arcos 5 y 9)
    NarrativeMission(
      id: 'disolucion_1',
      title: 'Observa tu ego hablando',
      description: 'Durante una conversación, observa cómo habla tu ego sin intervenir.',
      principle: 'Reprogramación mental',
      arc: Arc.disolucion,
      phase: 5,
      order: 1,
      difficulty: Difficulty.medium,
      xpReward: 25,
      coinsReward: 5,
      tags: ['ego', 'observación'],
    ),
    NarrativeMission(
      id: 'disolucion_2',
      title: 'Disuelve una emoción recurrente',
      description: 'Trabaja activamente para liberar una emoción que te limita recurrentemente.',
      principle: 'Reprogramación mental',
      arc: Arc.disolucion,
      phase: 5,
      order: 2,
      difficulty: Difficulty.hard,
      xpReward: 35,
      coinsReward: 7,
      tags: ['emociones', 'liberación'],
    ),
    NarrativeMission(
      id: 'disolucion_3',
      title: 'Reto: 3 días sin resolver nada',
      description: 'Durante 72 horas, no intentes resolver problemas, solo obsérvalos.',
      principle: 'Reprogramación mental',
      arc: Arc.disolucion,
      phase: 5,
      order: 3,
      difficulty: Difficulty.hard,
      xpReward: 40,
      coinsReward: 8,
      tags: ['reto', 'observación'],
    ),
    NarrativeMission(
      id: 'disolucion_4',
      title: 'Redefine el éxito en tus términos',
      description: 'Reescribe tu definición personal de éxito alejada de estándares externos.',
      principle: 'Desapego emocional',
      arc: Arc.disolucion,
      phase: 5,
      order: 4,
      difficulty: Difficulty.medium,
      xpReward: 25,
      coinsReward: 5,
      tags: ['éxito', 'redefinición'],
    ),
    NarrativeMission(
      id: 'disolucion_5',
      title: 'Practica "no acción eficaz"',
      description: 'Dedica tiempo a no hacer nada conscientemente, sin distracciones.',
      principle: 'Desapego emocional',
      arc: Arc.disolucion,
      phase: 5,
      order: 5,
      difficulty: Difficulty.medium,
      xpReward: 25,
      coinsReward: 5,
      tags: ['no-acción', 'presencia'],
    ),
    NarrativeMission(
      id: 'disolucion_6',
      title: 'Crea tu mantra NK personal',
      description: 'Desarrolla un mantra que encapsule tu camino Kaizeneka personal.',
      principle: 'Desapego emocional',
      arc: Arc.disolucion,
      phase: 5,
      order: 6,
      difficulty: Difficulty.medium,
      xpReward: 20,
      coinsReward: 4,
      tags: ['mantra', 'personal'],
    ),
    NarrativeMission(
      id: 'disolucion_7',
      title: 'Una semana sin dopamina basura',
      description: 'Elimina todas las fuentes de gratificación instantánea artificial por 7 días.',
      principle: 'Paz interior',
      arc: Arc.disolucion,
      phase: 5,
      order: 7,
      difficulty: Difficulty.hard,
      xpReward: 40,
      coinsReward: 8,
      tags: ['dopamina', 'desintoxicación'],
    ),
    NarrativeMission(
      id: 'disolucion_8',
      title: 'Mide tu paz interior diaria',
      description: 'Registra tu nivel de paz interior en una escala del 1 al 10 cada día.',
      principle: 'Paz interior',
      arc: Arc.disolucion,
      phase: 5,
      order: 8,
      difficulty: Difficulty.easy,
      xpReward: 15,
      coinsReward: 3,
      tags: ['paz', 'medición'],
    ),
    NarrativeMission(
      id: 'disolucion_9',
      title: 'Aprende a no reaccionar',
      description: 'Durante situaciones desafiantes, practica la no-reacción consciente.',
      principle: 'Paz interior',
      arc: Arc.disolucion,
      phase: 5,
      order: 9,
      difficulty: Difficulty.hard,
      xpReward: 30,
      coinsReward: 6,
      tags: ['no-reacción', 'paciencia'],
    ),
    NarrativeMission(
      id: 'disolucion_10',
      title: 'Gratitud radical diaria',
      description: 'Practica la gratitud por absolutamente todo, incluyendo lo negativo.',
      principle: 'Paz interior',
      arc: Arc.disolucion,
      phase: 5,
      order: 10,
      difficulty: Difficulty.medium,
      xpReward: 20,
      coinsReward: 4,
      tags: ['gratitud', 'radical'],
    ),

    // FASE 6 – SOBRADEZ (Arcos 6 y 10)
    NarrativeMission(
      id: 'sobradez_1',
      title: 'Vive un día desde tu versión sobrada',
      description: 'Actúa durante 24 horas como si ya fueras la versión más confiada de ti mismo.',
      principle: 'Liderazgo y coherencia',
      arc: Arc.sobradez,
      phase: 6,
      order: 1,
      difficulty: Difficulty.hard,
      xpReward: 35,
      coinsReward: 7,
      tags: ['confianza', 'versión-sobrada'],
    ),
    NarrativeMission(
      id: 'sobradez_2',
      title: 'Elimina toda excusa 24h',
      description: 'Durante un día completo, enfréntate a cada excusa con acción inmediata.',
      principle: 'Liderazgo y coherencia',
      arc: Arc.sobradez,
      phase: 6,
      order: 2,
      difficulty: Difficulty.hard,
      xpReward: 35,
      coinsReward: 7,
      tags: ['excusas', 'acción'],
    ),
    NarrativeMission(
      id: 'sobradez_3',
      title: 'Reto: No reaccionar bajo presión',
      description: 'Mantén la calma y la coherencia durante situaciones de alta presión.',
      principle: 'Liderazgo y coherencia',
      arc: Arc.sobradez,
      phase: 6,
      order: 3,
      difficulty: Difficulty.hard,
      xpReward: 40,
      coinsReward: 8,
      tags: ['presión', 'calma'],
    ),
    NarrativeMission(
      id: 'sobradez_4',
      title: 'Alinea tus tres JVCs conscientemente',
      description: 'Toma decisiones que beneficien simultáneamente tus tres áreas vitales.',
      principle: 'Acción equilibrada',
      arc: Arc.sobradez,
      phase: 6,
      order: 4,
      difficulty: Difficulty.medium,
      xpReward: 25,
      coinsReward: 5,
      tags: ['alineación', 'jvc'],
    ),
    NarrativeMission(
      id: 'sobradez_5',
      title: 'Diseña tu "Misión Sobrada"',
      description: 'Crea una declaración de propósito que te impulse hacia adelante.',
      principle: 'Acción equilibrada',
      arc: Arc.sobradez,
      phase: 6,
      order: 5,
      difficulty: Difficulty.medium,
      xpReward: 25,
      coinsReward: 5,
      tags: ['misión', 'propósito'],
    ),
    NarrativeMission(
      id: 'sobradez_6',
      title: 'Lidera con presencia',
      description: 'Dirige situaciones con confianza y claridad, sin necesidad de controlar.',
      principle: 'Acción equilibrada',
      arc: Arc.sobradez,
      phase: 6,
      order: 6,
      difficulty: Difficulty.medium,
      xpReward: 25,
      coinsReward: 5,
      tags: ['liderazgo', 'presencia'],
    ),
    NarrativeMission(
      id: 'sobradez_7',
      title: 'Aplica foco estratégico una semana',
      description: 'Trabaja solo en lo que realmente importa durante 7 días.',
      principle: 'Acción equilibrada',
      arc: Arc.sobradez,
      phase: 6,
      order: 7,
      difficulty: Difficulty.hard,
      xpReward: 35,
      coinsReward: 7,
      tags: ['foco', 'estratégico'],
    ),
    NarrativeMission(
      id: 'sobradez_8',
      title: 'Enseña sin predicar',
      description: 'Comparte conocimientos con otros sin intentar convencerlos.',
      principle: 'Servicio y legado',
      arc: Arc.sobradez,
      phase: 6,
      order: 8,
      difficulty: Difficulty.medium,
      xpReward: 20,
      coinsReward: 4,
      tags: ['enseñanza', 'compartir'],
    ),
    NarrativeMission(
      id: 'sobradez_9',
      title: 'Crea un mini dojo con otro usuario',
      description: 'Ayuda a otro usuario en su camino Kaizeneka durante una semana.',
      principle: 'Servicio y legado',
      arc: Arc.sobradez,
      phase: 6,
      order: 9,
      difficulty: Difficulty.medium,
      xpReward: 25,
      coinsReward: 5,
      tags: ['mentoría', 'comunidad'],
    ),
    NarrativeMission(
      id: 'sobradez_10',
      title: 'Integra el fracaso como maestro',
      description: 'Aprende activamente de cada error o fracaso que experimentes.',
      principle: 'Servicio y legado',
      arc: Arc.sobradez,
      phase: 6,
      order: 10,
      difficulty: Difficulty.medium,
      xpReward: 20,
      coinsReward: 4,
      tags: ['aprendizaje', 'fracaso'],
    ),

    // FASE 7 – TRASCENDENCIA (Arcos 11 y 12)
    NarrativeMission(
      id: 'trascendencia_1',
      title: 'Crea una Misión de Impacto Global',
      description: 'Define cómo contribuirás al mundo más allá de tu beneficio personal.',
      principle: 'Servicio y legado',
      arc: Arc.trascendencia,
      phase: 7,
      order: 1,
      difficulty: Difficulty.hard,
      xpReward: 40,
      coinsReward: 8,
      tags: ['impacto', 'global'],
    ),
    NarrativeMission(
      id: 'trascendencia_2',
      title: 'Dona XP a otro usuario',
      description: 'Comparte tus puntos de experiencia con alguien que lo necesite.',
      principle: 'Servicio y legado',
      arc: Arc.trascendencia,
      phase: 7,
      order: 2,
      difficulty: Difficulty.easy,
      xpReward: 15,
      coinsReward: 3,
      tags: ['donación', 'comunidad'],
    ),
    NarrativeMission(
      id: 'trascendencia_3',
      title: 'Enseña un principio NK públicamente',
      description: 'Comparte un principio Kaizeneka con tu comunidad o red social.',
      principle: 'Servicio y legado',
      arc: Arc.trascendencia,
      phase: 7,
      order: 3,
      difficulty: Difficulty.medium,
      xpReward: 25,
      coinsReward: 5,
      tags: ['enseñanza', 'público'],
    ),
    NarrativeMission(
      id: 'trascendencia_4',
      title: 'Escribe tu "Carta del Sensei"',
      description: 'Redacta una carta a tu yo futuro compartiendo tu sabiduría adquirida.',
      principle: 'Disolución del ego',
      arc: Arc.trascendencia,
      phase: 7,
      order: 4,
      difficulty: Difficulty.medium,
      xpReward: 25,
      coinsReward: 5,
      tags: ['carta', 'futuro'],
    ),
    NarrativeMission(
      id: 'trascendencia_5',
      title: 'Vive un día sin validación externa',
      description: 'Realiza actividades por puro disfrute interno, sin compartirlas.',
      principle: 'Disolución del ego',
      arc: Arc.trascendencia,
      phase: 7,
      order: 5,
      difficulty: Difficulty.hard,
      xpReward: 35,
      coinsReward: 7,
      tags: ['validación', 'interno'],
    ),
    NarrativeMission(
      id: 'trascendencia_6',
      title: 'Practica el Silencio 24h',
      description: 'Mantén silencio absoluto durante 24 horas, comunicándote solo lo esencial.',
      principle: 'Disolución del ego',
      arc: Arc.trascendencia,
      phase: 7,
      order: 6,
      difficulty: Difficulty.hard,
      xpReward: 40,
      coinsReward: 8,
      tags: ['silencio', 'presencia'],
    ),
    NarrativeMission(
      id: 'trascendencia_7',
      title: 'Lidera una tribu Kaizeneka',
      description: 'Forma o únete a un grupo de practicantes para guiar colectivamente.',
      principle: 'Cierre del ciclo vital NK',
      arc: Arc.trascendencia,
      phase: 7,
      order: 7,
      difficulty: Difficulty.hard,
      xpReward: 40,
      coinsReward: 8,
      tags: ['liderazgo', 'comunidad'],
    ),
    NarrativeMission(
      id: 'trascendencia_8',
      title: 'Disuelve la dualidad éxito-fracaso',
      description: 'Practica ver todas las experiencias como igualmente valiosas.',
      principle: 'Cierre del ciclo vital NK',
      arc: Arc.trascendencia,
      phase: 7,
      order: 8,
      difficulty: Difficulty.hard,
      xpReward: 35,
      coinsReward: 7,
      tags: ['dualidad', 'aceptación'],
    ),
    NarrativeMission(
      id: 'trascendencia_9',
      title: 'Meditación lúcida diaria',
      description: 'Practica meditación consciente durante 20 minutos cada día por una semana.',
      principle: 'Cierre del ciclo vital NK',
      arc: Arc.trascendencia,
      phase: 7,
      order: 9,
      difficulty: Difficulty.medium,
      xpReward: 30,
      coinsReward: 6,
      tags: ['meditación', 'diaria'],
    ),
    NarrativeMission(
      id: 'trascendencia_10',
      title: 'Transmite el legado Kaizeneka',
      description: 'Encuentra formas creativas de compartir los principios con las nuevas generaciones.',
      principle: 'Cierre del ciclo vital NK',
      arc: Arc.trascendencia,
      phase: 7,
      order: 10,
      difficulty: Difficulty.medium,
      xpReward: 25,
      coinsReward: 5,
      tags: ['legado', 'transmisión'],
    ),
  ];

  // Obtener misiones disponibles para un usuario
  static Future<List<NarrativeMission>> getAvailableMissions(String userId, int currentLevel, int currentArc, List<String> completedMissions) async {
    final allMissions = await getAllMissions();
    return allMissions.where((mission) {
      // Verificar si ya está completada
      if (completedMissions.contains(mission.id)) return false;

      // Verificar nivel mínimo requerido (aproximadamente nivel = fase * 2)
      if (currentLevel < (mission.phase * 2)) return false;

      // Verificar arco actual
      if (mission.arc.index > currentArc) return false;

      // Verificar prerrequisitos de orden en la fase
      final phaseMissions = allMissions.where((m) => m.phase == mission.phase && m.arc == mission.arc).toList();
      final previousMissions = phaseMissions.where((m) => m.order < mission.order).toList();

      // Todas las misiones anteriores deben estar completadas
      return previousMissions.every((prevMission) => completedMissions.contains(prevMission.id));
    }).toList();
  }

  // Obtener misiones completadas
  static Future<List<NarrativeMission>> getCompletedMissions(List<String> completedMissionIds) async {
    final allMissions = await getAllMissions();
    return allMissions.where((mission) => completedMissionIds.contains(mission.id)).toList();
  }

  // Obtener progreso de arco
  static Future<Map<String, dynamic>> getArcProgress(int currentArc, List<String> completedMissions) async {
    final arc = Arc.values[currentArc];
    final allMissions = await getAllMissions();
    final arcMissions = allMissions.where((mission) => mission.arc == arc).toList();
    final completedArcMissions = arcMissions.where((mission) => completedMissions.contains(mission.id)).length;

    return {
      'arc': arc,
      'totalMissions': arcMissions.length,
      'completedMissions': completedArcMissions,
      'progress': arcMissions.isEmpty ? 0.0 : completedArcMissions / arcMissions.length,
    };
  }

  // Verificar si se puede avanzar al siguiente arco
  static Future<bool> canAdvanceArc(int currentArc, List<String> completedMissions) async {
    final currentArcEnum = Arc.values[currentArc];
    final allMissions = await getAllMissions();
    final arcMissions = allMissions.where((mission) => mission.arc == currentArcEnum).toList();
    final completedArcMissions = arcMissions.where((mission) => completedMissions.contains(mission.id)).length;

    // Se necesita completar al menos el 80% de las misiones del arco actual
    return completedArcMissions >= (arcMissions.length * 0.8);
  }

  // Get user narrative progress
  static Future<List<String>> getUserCompletedMissions(String userId) async {
    try {
      final response = await SupabaseService.client
          .from('user_narrative_progress')
          .select('mission_id')
          .eq('user_id', userId)
          .eq('is_completed', true);

      return response.map<String>((json) => json['mission_id'] as String).toList();
    } catch (e) {
      debugPrint('Error fetching user completed missions: $e');
      return [];
    }
  }

  // Mark mission as completed for user
  static Future<void> completeMissionForUser(String userId, String missionId) async {
    try {
      await SupabaseService.client
          .from('user_narrative_progress')
          .upsert({
            'user_id': userId,
            'mission_id': missionId,
            'is_unlocked': true,
            'is_completed': true,
            'completed_at': DateTime.now().toIso8601String(),
            'updated_at': DateTime.now().toIso8601String(),
          }, onConflict: 'user_id,mission_id');
    } catch (e) {
      debugPrint('Error completing mission for user: $e');
    }
  }

  // Unlock mission for user
  static Future<void> unlockMissionForUser(String userId, String missionId) async {
    try {
      await SupabaseService.client
          .from('user_narrative_progress')
          .upsert({
            'user_id': userId,
            'mission_id': missionId,
            'is_unlocked': true,
            'updated_at': DateTime.now().toIso8601String(),
          }, onConflict: 'user_id,mission_id');
    } catch (e) {
      debugPrint('Error unlocking mission for user: $e');
    }
  }
}